---

- name: "configuration play." 
  hosts: web
  user: ec2-user # ubuntu
  become: true
  become_method: sudo
  become_user: root  
  gather_facts: false
  vars:
    - ansible_python_interpreter: /bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: wait for server
      wait_for_connection:
        timeout: 120 # 600
        
  roles:
    - deploy
# - name: "configuration play." 
#   hosts: web
#   user: ubuntu
#   gather_facts: false
#   vars:
#     - ansible_python_interpreter: /usr/bin/python3
#     - ansible_host_key_checking: false
#     - ansible_stdout_callback: yaml
#   roles:
#     - deploy
