---
- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: download & install nodejs 13
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_13.x | sudo -E bash -
    sudo apt-get install -y nodejs

# - name: "install nodejs 13"
#   become: true
#   apt:
#     name: ["nodejs","npm"]
#     state: latest
#     update_cache: yes

- name: "install pm."
  become: true
  npm:
    name: pm
    global: yes
    production: yes
    state: latest

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: latest
# ---
# - name: "upgrade packages."
#   become: true
#   yum:
#     name: '*'
#     state: latest

# - name: "install python 3."
#   become: true
#   yum:
#     name: 'python3'
#     state: latest
#     update_cache: yes

# - name: "install nodejs."
#   become: true
#   shell: |
#     sudo yum install -y gcc-c++ make
#     curl -sL https://rpm.nodesource.com/setup_13.x | sudo -E bash -
#     sudo yum install -y nodejs
# # #    sudo yum install nodejs npm --skip-broken 

# # - name: "install nodejs"
# #   become: true
# #   yum:
# #     name: 
# #       - nodejs
# #     state: latest
# # #    skip_broken: yes
# #     lock_timeout: 60
# #     update_cache: yes

# - name: "install pm"
#   become: true
#   npm:
#     name: pm
#     global: yes
#     production: yes
#     state: present

# - name: "install pm2"
#   become: true
#   npm:
#     name: pm2
#     global: yes
#     production: yes
#     state: present